### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [taneli-salonen1/gtm-pardot-tracking-get-request#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) There is no homepage url mentioned in the metadata file. Please mention homepage url.

**Comment by taneli-salonen1** [comment]
Hi @praveena-pappu Thanks for reviewing the template. I've added a homepage link.

I've also changed my GitHub user name to show my actual name in the template gallery instead of the nickname I previously had.

Would it be possible to adjust the GitHub URL in the template gallery to this new URL?
https://github.com/taneli-salonen1/gtm-pardot-tracking-get-request

**Comment by taneli-salonen1** [comment]
Nevermind, that seems to have solved automatically. :)
